Repository hazelcast/hz-docs, pull requests merged in 2022-11, with the labels that each got.

#581 Adding content for JSON_ARRAYAGG and JSON_OBJECTAGG
  docs/modules/sql/pages/functions-and-operators.adoc
  docs/modules/sql/pages/working-with-json.adoc
Labels: backport to 5.2

#584 Unify serialization mechanisms in the entry listener with predicate documentation API-1572
  docs/modules/ROOT/examples/dds/map/Employee.java
  docs/modules/ROOT/examples/dds/map/ListenerWithPredicate.java
  docs/modules/data-structures/pages/listening-for-map-entries.adoc
Labels: documentation, backport to 5.1, backport to 5.0, Source: Internal, backport to 5.2

#596 Fix typo in JSON_VALUE function syntax
  docs/modules/sql/pages/functions-and-operators.adoc
Labels: backport to 5.2

#597 Fixes #594 Enterprise JDBC Connector support
  docs/modules/sql/pages/mapping-to-jdbc.adoc
Labels: backport to all versions

#602 DOCS-238 Corrects setTtl method
  docs/modules/data-structures/pages/managing-map-memory.adoc
Labels: backport to all versions

#601 Fixes #595 Downsides of using Cluster Safe Option in Health Check
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: backport to all versions

#605 DOCS-315 Option name incorrect in HZ healthcheck script
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: backport to all versions

#609 [DOCS-314] - Ensuring alphabetical order of sys props and started adding missing o…
  docs/modules/ROOT/pages/system-properties.adoc
Labels: backport to 5.2
