Repository hazelcast/hz-docs, pull requests merged in 2022-08, with the labels that each got.

#493 Rename Azul JDKs according to the new branding
  docs/modules/deploy/pages/supported-jvms.adoc
Labels: backport to all versions

#496 DOCS-169_Cluster_Version_Mismatch_Delta-WAN_Sync
  docs/modules/wan/pages/advanced-features.adoc
Labels: backport to all versions

#501 Use Platform as product title
  docs/antora.yml
Labels: backport to all versions

#502 Replace default JCache names with a wildcard
  docs/modules/data-structures/pages/event-journal.adoc
  docs/modules/integrate/pages/map-connector.adoc
  docs/modules/jcache/pages/icache.adoc
  docs/modules/jcache/pages/setup.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
  docs/modules/network-partitioning/pages/split-brain-recovery.adoc
Labels: backport to all versions

#495 Added ListenerWithPredicate sample for Go. [API-1485]
  docs/modules/data-structures/pages/listening-for-map-entries.adoc
Labels: documentation, good first issue, Source: Internal

#500 DOCS-248 Add troubleshooting for creating mappings in SQL
  docs/modules/sql/pages/troubleshooting.adoc
Labels: backport to beta

#498 DOCS-213 Clarify Differences in Persistence
  docs/modules/storage/pages/high-density-memory.adoc
Labels: backport to all versions, backport to beta

#516 DOCS-214 Persistence of SQL metatadata
  docs/modules/sql/pages/sql-overview.adoc
  docs/modules/storage/pages/persistence.adoc
Labels: backport to 5.1, backport to 5.0

#510 Adding content for dynamically updating member list feature.
  docs/modules/maintain-cluster/pages/rest-api.adoc
  docs/modules/network-partitioning/pages/split-brain-recovery.adoc
Labels: backport to beta

#514 Add External Data Store documentation [HZ-1260]
  docs/modules/ROOT/nav.adoc
  docs/modules/cache/pages/overview.adoc
  docs/modules/configuration/pages/dynamic-config.adoc
  docs/modules/data-structures/pages/working-with-external-data.adoc
  docs/modules/external-data-stores/pages/external-data-stores.adoc
  docs/modules/external-data-stores/partials/nav.adoc
  docs/modules/integrate/pages/jdbc-connector.adoc
  docs/modules/spring/pages/configuration.adoc
Labels: backport to beta
