Repository hazelcast/hz-docs, pull requests merged in 2022-07, with the labels that each got.

#488 Fix SINK INTO example
  docs/modules/sql/pages/sink-into.adoc
Labels: backport to all versions

#484 syntax fix
  docs/modules/sql/pages/querying-streams.adoc
Labels: backport to 5.1

#486 Fix examples for HOST_AWARE partition group type
  docs/modules/clusters/pages/partition-group-configuration.adoc
Labels: forwardport to snapshot
