Repository hazelcast/hz-docs, pull requests merged in 2022-10, with the labels that each got.

#548 #542 Feedback for Mapping to JDBC
  docs/modules/sql/pages/mapping-to-jdbc.adoc
Labels: backport to beta

#550 Apply reviewer's suggestions
  docs/modules/external-data-stores/pages/external-data-stores.adoc
  docs/modules/mapstore/pages/configuration-guide.adoc
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
  docs/modules/mapstore/pages/working-with-external-data.adoc
Labels: backport to beta

#551 Avoid server side class in the client side code
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
Labels: backport to beta

#552 #545 Feedback for Distributed Map Page
  docs/modules/data-structures/pages/map.adoc
Labels: backport to all versions

#559 #481 Resolved Typo on Mapping to a File System page
  docs/modules/sql/pages/mapping-to-a-file-system.adoc
Labels: backport to all versions

#560 Fixes#424 Adding links to Ingesting Data from External Sources page
  docs/modules/ingest/pages/overview.adoc
Labels: backport to all versions

#555 Fix examples showing the weak password banners
  docs/modules/security/pages/validating-secrets.adoc
Labels: backport to all versions

#561 Fixes #441
  docs/modules/ROOT/images/HighLevelArch.png
Labels: backport to all versions

#562 Fixes #482 Removal of empty tabs
  docs/modules/data-structures/pages/listening-for-map-entries.adoc
Labels: backport to all versions

#564 Fixes #530 AP and CP abbreviations replaced in table
  docs/modules/data-structures/pages/distributed-data-structures.adoc
Labels: backport to all versions

#573 Add documentation about running with persistence in k8s
  docs/modules/deploy/pages/configuring-kubernetes.adoc
Labels: backport to 5.2

#572 #421 Workaround for no automatic reconnection to primary cluster
  docs/modules/getting-started/pages/blue-green.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2
