Repository hazelcast/hz-docs, pull requests merged in 2022-12, with the labels that each got.

#618 Fixes #613 Typo High Density Memory Store page
  docs/modules/storage/pages/high-density-memory.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#622 DOCS-337 Update bitmap example for creating an index
  docs/modules/sql/pages/create-index.adoc
Labels: backport to 5.1, backport to 5.2

#624 Directing users to the CLC documentation.
  docs/antora.yml
  docs/modules/clients/pages/clc.adoc
Labels: backport to 5.2

#625 Adding description of stdout prop for Diagnostics.
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#554 [API-1530] Update Compact serialization documentation
  docs/modules/serialization/pages/compact-serialization.adoc
Labels: backport to 5.2

#619 Increase width for mapping parameter examples
  docs/modules/sql/pages/create-mapping.adoc
Labels: backport to 5.2

#626 Adding the missing discovery options content.
  docs/modules/ROOT/nav.adoc
Labels: backport to 5.1, backport to 5.2

#629 Adding capacity element description along with minor simplifications.
  docs/modules/tiered-storage/pages/configuration.adoc
Labels: backport to 5.1, backport to 5.2

#630 Adding missing member-list element.
  docs/modules/clusters/pages/discovering-by-tcp.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2
