Repository hazelcast/hz-docs, pull requests merged in 2023-09, with the labels that each got.

#835 Add section about Deny permissions to Client Security [HZ-2780]
  .gitignore
  docs/modules/security/pages/native-client-security.adoc
Labels: documentation

#839 [DOCS-595] Fixing unresolved cross-reference in Persistence configuration content.
  docs/modules/storage/pages/configuring-persistence.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#834 Started to draft the DMT content.
  docs/modules/migrate/pages/data-migration-tool.adoc
  docs/modules/migrate/partials/nav.adoc
Labels: backport to 5.3

#798 CP Subsystem Content Improvements
  docs/modules/ROOT/examples/dds/ExampleIAtomicReference.java
  docs/modules/ROOT/examples/dds/iatomiclong/ExampleIAtomicLong.java
  docs/modules/ROOT/examples/dds/iatomiclong/IAtomicLongExecuteFuncs.java
  docs/modules/ROOT/examples/dds/semaphore/SemaphoreMember.java
  docs/modules/cp-subsystem/pages/best-practices.adoc
  docs/modules/cp-subsystem/pages/configuration.adoc
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
  docs/modules/cp-subsystem/pages/management.adoc
  docs/modules/cp-subsystem/partials/nav.adoc
  docs/modules/data-structures/pages/distributed-data-structures.adoc
  docs/modules/data-structures/pages/fencedlock.adoc
  docs/modules/data-structures/pages/iatomiclong.adoc
  docs/modules/data-structures/pages/iatomicreference.adoc
  docs/modules/data-structures/pages/icountdownlatch.adoc
  docs/modules/data-structures/pages/isemaphore.adoc
Labels: backport to 5.1, backport to 5.0, Type: Enhancement, backport to 5.2, backport to 5.3

#849 Replace `MemorySize` with `Capacity`
  docs/modules/ROOT/examples/storage/SampleHDConfiguration.java
  docs/modules/storage/pages/high-density-memory.adoc
Labels: backport to 5.1, backport to 5.2, backport to 5.3

#856 Fixes #855
  docs/modules/clients/pages/hazelcast-clients.adoc
Labels: backport to all versions

#857 Fixing broken external links for all 5.x series
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/integrate/pages/elasticsearch-connector.adoc
  docs/modules/jcache/pages/tck.adoc
  docs/modules/kubernetes/pages/deploying-in-kubernetes.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#853 Drafting the ExtendedMapEntry Content.
  docs/modules/computing/pages/entry-processor.adoc
Labels: backport to 5.2, backport to 5.3

#861 Backporting Kubernetes restructure to 5.0 and 5.1 docs.
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/clusters/pages/discovery-mechanisms.adoc
  docs/modules/clusters/pages/network-configuration.adoc
  docs/modules/clusters/pages/partition-group-configuration.adoc
  docs/modules/deploy/pages/deploying-in-cloud.adoc
  docs/modules/deploy/pages/scaling-and-upgrading-kubernetes.adoc
  docs/modules/deploy/partials/nav.adoc
  docs/modules/getting-started/pages/editions.adoc
  docs/modules/getting-started/pages/get-started-docker.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/kubernetes/pages/deploying-in-kubernetes.adoc
  docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
  docs/modules/kubernetes/pages/helm-configuring-ssl.adoc
  docs/modules/kubernetes/pages/helm-dynamic-persistence-configuration.adoc
  docs/modules/kubernetes/pages/helm-enabling-external-access.adoc
  docs/modules/kubernetes/pages/helm-hazelcast-chart.adoc
  docs/modules/kubernetes/pages/helm-hazelcast-enterprise-chart.adoc
  docs/modules/kubernetes/pages/kubernetes-auto-discovery.adoc
  docs/modules/kubernetes/pages/troubleshooting-and-limitations.adoc
  docs/modules/kubernetes/partials/nav.adoc
  docs/modules/wan/pages/defining-wan-replication.adoc
Labels: backport to 5.0

#862 [DOCS-590]: Serialization content improvements
  docs/modules/serialization/pages/implementing-dataserializable.adoc
  docs/modules/serialization/pages/implementing-identifieddataserializable.adoc
  docs/modules/serialization/pages/serialization.adoc
  docs/modules/serialization/partials/nav.adoc
Labels: backport to 5.2, backport to 5.3
