Repository hazelcast/hz-docs, pull requests merged in 2023-12, with the labels that each got.

#913 Partition pruning documentation
  docs/modules/sql/pages/partition-pruning.adoc
  docs/modules/sql/partials/nav.adoc
Labels: Source: Internal, Team: Platform

#916 Removing obsolete pages
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/architecture/pages/design-docs.adoc
  docs/modules/cache/partials/nav.adoc
  docs/modules/cluster-performance/pages/best-practices.adoc
  docs/modules/clusters/pages/logging-configuration.adoc
  docs/modules/clusters/pages/setting-up-clusters.adoc
  docs/modules/clusters/partials/clusters-nav.adoc
  docs/modules/configuration/pages/checking-configuration.adoc
  docs/modules/configuration/pages/configuring-declaratively.adoc
  docs/modules/configuration/pages/understanding-configuration.adoc
  docs/modules/getting-started/pages/get-started-cli.adoc
  docs/modules/integrate/pages/data-structure-connectors.adoc
  docs/modules/maintain-cluster/pages/logging.adoc
  docs/modules/performance/pages/back-pressure.adoc
  docs/modules/performance/pages/best-practices.adoc
  docs/modules/performance/pages/cpu-thread-affinity.adoc
  docs/modules/performance/pages/data-affinity.adoc
  docs/modules/performance/pages/near-cache.adoc
  docs/modules/performance/pages/performance.adoc
  docs/modules/performance/pages/pipelining.adoc
  docs/modules/performance/pages/running-on-ec2.adoc
  docs/modules/performance/pages/slowoperationdetector.adoc
  docs/modules/performance/pages/threading-model.adoc
  docs/modules/pipelines/pages/building-pipelines.adoc
  docs/modules/pipelines/pages/event-time.adoc
Labels: backport to 5.2, backport to 5.3

#915 Updating shutdown hook description.
  docs/modules/ROOT/pages/system-properties.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#922 Updating API support for WAN dynamic configuration.
  docs/modules/configuration/pages/dynamic-config.adoc
Labels: backport to 5.2, backport to 5.3

#914 Add note about compact serialization not supported
  docs/modules/migrate/pages/data-migration-tool.adoc
Labels: backport to 5.3

#924 Simplifying Phi Accrual and Deadline Failure Detectors content.
  docs/modules/clusters/pages/deadline-detector.adoc
  docs/modules/clusters/pages/phi-accrual-detector.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#934 [DOCS-704] Add warning to Spring configuration section about transact…
  docs/modules/spring/pages/configuration.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#935 Adding note about license key persistence.
  docs/modules/deploy/pages/enterprise-licenses.adoc
Labels: backport to 5.1, backport to 5.2, backport to 5.3

#928 DOCS-701 Improvements to editions/installation
  docs/modules/getting-started/pages/editions.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#939 Improvements on various metrics ...
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to 5.3

#942 Adding the transactions deprecation notice to all 5.x series.
  docs/modules/transactions/pages/creating-a-transaction-interface.adoc
Labels: backport to 5.1, backport to 5.0

#940 Fix a typo
  docs/modules/getting-started/pages/get-started-docker.adoc
Labels: forwardport to snapshot
