Repository hazelcast/hz-docs, pull requests merged in 2023-10, with the labels that each got.

#863 Clarify that external connectors should use some other means to protect access [HZ-2991]
  docs/modules/pipelines/pages/job-security.adoc
  docs/modules/security/pages/native-client-security.adoc
Labels: backport to 5.3

#867 Simplifying supported JDK content.
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: bug

#868 Making eviction notice more highlighted for Hazelcast JCache.
  docs/modules/jcache/pages/icache.adoc
Labels: backport to 5.2, backport to 5.3

#870 [DOCS-654] Fixes unit value.
  docs/modules/cp-subsystem/pages/configuration.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#869 Adding missing configuration options for Scheduled Executor Service.
  docs/modules/ROOT/examples/distributedcomputing/ScheduledExecutorConfiguration.java
  docs/modules/computing/pages/scheduled-executor-service.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#875 Fixes #644
  docs/modules/storage/pages/configuring-persistence.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#876 Fixes #614
  docs/modules/ROOT/pages/system-properties.adoc
  docs/modules/configuration/pages/configuring-with-system-properties.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#877 CPGroupAvailabilityEvent Publication on Graceful Shutdown [HZ-3118]
  docs/modules/cp-subsystem/pages/management.adoc
Labels: documentation

#879 Fixes #515
  docs/modules/pipelines/pages/stream-processing-client.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#864 WAN additions & Advanced Features tweaks [HZ-3386]
  docs/modules/wan/pages/advanced-features.adoc
  docs/modules/wan/pages/modes.adoc
Labels: documentation, backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#880 Fixes #837
  docs/modules/clients/pages/java.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#884 Fix Platform versions in antora.yml to 5.3.5
  docs/antora.yml
Labels: bug, Source: Internal, Team: Platform, backport to 5.3

#885 Fixes #711
  docs/modules/ROOT/pages/system-properties.adoc
  docs/modules/network-partitioning/pages/split-brain-recovery.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#886 Fix WAN advanced network YML example indentation
  docs/modules/wan/pages/advanced-features.adoc
Labels: documentation, backport to all versions

#883 Simplifying the Metrics reference.
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to 5.3

#887 Update: no requirement to enable compact serialization
  docs/modules/serialization/pages/serialization.adoc
Labels: forwardport to snapshot, Source: Internal, backport to 5.2
