Repository hazelcast/hz-docs, pull requests merged in 2023-08, with the labels that each got.

#806 Update getting started Docker run command
  docs/modules/deploy/pages/deploying-with-docker.adoc
  docs/modules/deploy/partials/docker-ip-warning.adoc
  docs/modules/getting-started/pages/blue-green.adoc
  docs/modules/getting-started/pages/get-started-docker.adoc
  docs/modules/getting-started/pages/persistence.adoc
  docs/modules/getting-started/pages/wan.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#817 Fix the IPv6 note in Network Configuration page
  docs/modules/clusters/pages/network-configuration.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#820 DOCS-497 Remove BETA flag from data connections page
  docs/modules/data-connections/pages/data-connections-configuration.adoc
Labels: backport to 5.3

#821 Enhancing the client lib step description for JMS connector.
  docs/modules/integrate/pages/jms-connector.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#824 Fix Jet dependency for Maven project creation.
  docs/modules/pipelines/pages/python.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#822 DOCS-568 Product Renaming
  antora-playbook-local.yml
  antora-playbook.yml
  docs/modules/clients/pages/java.adoc
  docs/modules/deploy/pages/choosing-a-deployment-option.adoc
  docs/modules/deploy/pages/deploying-in-cloud.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
Labels: documentation, backport to 5.1, backport to 5.2, backport to 5.3

#802 Add WAN eviction cluster properties [HZ-2619]
  docs/modules/ROOT/pages/system-properties.adoc
  docs/modules/wan/pages/tuning.adoc
Labels: backport to 5.3

#770 DOCS-547 End of support for Elasticsearch 6
  docs/modules/integrate/pages/elasticsearch-connector.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
Labels: backport to 5.3

#800 Clarify SQL type assignment for numeric literals [HZ-1748]
  docs/modules/sql/pages/data-types.adoc
Labels: backport to 5.1, backport to 5.0, Type: Enhancement, backport to 5.2, backport to 5.3

#786 Describe composite indexes as a way of improving performance and limitations in EXPLAIN for nested loops join.
  docs/modules/sql/pages/create-index.adoc
  docs/modules/sql/pages/explain.adoc
  docs/modules/sql/pages/improving-performance.adoc
Labels: documentation, Source: Internal, backport to 5.2, backport to 5.3

#797 [CN-571] Restructure AWS discovery documentation
  docs/modules/deploy/pages/deploying-on-aws.adoc
Labels: backport to 5.3

#829 Fix System Properties reference position under Eviction in WAN Tuning
  docs/modules/wan/pages/tuning.adoc
Labels: documentation

#831 DOCS-630_SUP-223
  docs/modules/security/pages/native-client-security.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#836 Fix code formatting in `entry-processor.adoc`
  docs/modules/computing/pages/entry-processor.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3
