Repository hazelcast/hz-docs, pull requests merged in 2023-11, with the labels that each got.

#888 Fix for #882
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#891 Adding RN for Platform 5.3.6
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-3-6.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#892 Draft improvements to Using the DMT
  docs/modules/ROOT/images/dmt_diagram.png
  docs/modules/migrate/pages/data-migration-tool.adoc
Labels: backport to 5.3

#899 Update serialization2.png
  docs/modules/ROOT/images/serialization2.png
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#901 Fix broken code formatting
  docs/modules/ROOT/pages/faq.adoc
  docs/modules/query/pages/predicate-overview.adoc
Labels: backport to 5.1, backport to 5.2, backport to 5.3

#897 Improve RingbufferStore documentation
  docs/modules/data-structures/pages/ringbuffer.adoc
Labels: backport to 5.1, backport to 5.2, backport to 5.3

#906 Add CPMap Documentation [HZ-3650]
  docs/modules/ROOT/examples/cp/CpSubsystemAPI.java
  docs/modules/ROOT/examples/dds/cpmap/ExampleCPMap.java
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/clients/pages/java.adoc
  docs/modules/cp-subsystem/pages/configuration.adoc
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
  docs/modules/data-structures/pages/cpmap.adoc
  docs/modules/data-structures/pages/distributed-data-structures.adoc
  docs/modules/data-structures/partials/nav.adoc
Labels: documentation
