Repository hazelcast/hz-docs, pull requests merged in 2023-04, with the labels that each got.

#699 Add some necessary information to tutorial [API-1927]
  docs/modules/pipelines/pages/python.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#679 Adding TS metrics.
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: documentation

#715 DOCS-488 Corrected link on Managing Jobs page
  docs/modules/pipelines/pages/configuring-jobs.adoc
  docs/modules/pipelines/pages/job-management.adoc
Labels: documentation, backport to 5.1, backport to 5.0, backport to beta-2, backport to 5.2

#704 Cleaning up Logging Configuration content.
  docs/modules/maintain-cluster/pages/logging.adoc
Labels: backport to 5.1, backport to 5.0, backport to beta-2, backport to 5.2
