Repository hazelcast/hz-docs, pull requests merged in 2023-05, with the labels that each got.

#728 Update MapStore configuration-guide.adoc
  docs/modules/mapstore/pages/configuration-guide.adoc
Labels: documentation, Source: Internal

#702 DOCS-481 SQL Statements - Create and Drop Data Connections
  docs/modules/sql/pages/create-data-connection.adoc
  docs/modules/sql/pages/drop-data-connection.adoc
  docs/modules/sql/pages/sql-overview.adoc
  docs/modules/sql/pages/sql-statements.adoc
  docs/modules/sql/partials/nav.adoc
Labels: documentation

#718 Docs 482 CREATE MAPPING with a data connection
  docs/modules/sql/pages/create-mapping.adoc
Labels: documentation

#710 DOCS-441 SHOW RESOURCES statement
  docs/modules/sql/pages/show-resources.adoc
  docs/modules/sql/pages/sql-statements.adoc
  docs/modules/sql/partials/nav.adoc
Labels: documentation

#723 Update cluster-wide restart doc
  docs/modules/storage/images/full-cluster-restart.svg
  docs/modules/storage/pages/configuring-persistence.adoc
Labels: backport to 5.3

#734 Add mutualAuthentication field in OpenSSL page
  docs/modules/security/pages/integrating-openssl.adoc
Labels: backport to 5.2, backport to 5.3

#730 Adding content for Attributed Based Partitioning Strategy.
  docs/modules/performance/pages/data-affinity.adoc
Labels: documentation, backport to 5.3

#729 Remove specific netty and netty-tcnative versions from the integrating-openssl page
  docs/modules/security/pages/integrating-openssl.adoc
Labels: backport to 5.3

#708 Deleted kate swp files
  docs/modules/architecture/pages/.event-time-processing.adoc.kate-swp
  docs/modules/architecture/pages/.execution-engine.adoc.kate-swp
Labels: backport to 5.3

#739 DOCS-523 SQL Catalog Persistence draft
  docs/modules/ROOT/examples/storage/SampleHotRestartConfiguration.java
  docs/modules/data-connections/pages/data-connections-configuration.adoc
  docs/modules/sql/pages/sql-overview.adoc
  docs/modules/storage/pages/configuring-persistence.adoc
  docs/modules/storage/pages/persistence.adoc
Labels: documentation, backport to 5.3

#736 Add a note about the write method of the CompactSerializer [API-1948]
  docs/modules/serialization/pages/compact-serialization.adoc
Labels: backport to 5.2, backport to 5.3

#738 Clarify backup related properties for client
  docs/modules/clients/pages/java.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#752 Fixes #750
  docs/modules/pipelines/pages/cdc.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#754 Fixes #747
  docs/modules/pipelines/pages/cdc.adoc
  docs/modules/pipelines/pages/transforms.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3
