Repository hazelcast/hz-docs, pull requests merged in 2023-07, with the labels that each got.

#790 Add trial licence key link to the Hazelcast enterprise chart page
  docs/modules/kubernetes/pages/helm-hazelcast-enterprise-chart.adoc
Labels: backport to all versions, backport to 5.3

#787 Remove information that indexes cannot be created for TStore IMaps
  docs/modules/query/pages/indexing-maps.adoc
Labels: forwardport to snapshot

#788 Move "Improving Query Performance" just after Predicates API
  docs/modules/ROOT/nav.adoc
Labels: backport to 5.3

#795 Updating latest versions of clients.
  docs/antora.yml
Labels: backport to 5.3

#809 DOCS-597 Update Predicate Deprecation Statement
  docs/modules/query/pages/overview.adoc
  docs/modules/query/pages/predicate-overview.adoc
Labels: documentation, backport to 5.1, backport to 5.2, backport to 5.3

#813 DOCS-604 Correct examples
  docs/modules/sql/pages/create-data-connection.adoc
Labels: backport to 5.3
