Repository hazelcast/hz-docs, pull requests merged in 2023-03, with the labels that each got.

#671 Fix header styling in compact binary specification document
  docs/modules/ROOT/pages/compact-binary-specification.adoc
Labels: documentation, Source: Internal, backport to 5.2

#672 Adding sync/progress endpoint description.
  docs/modules/wan/pages/rest-api.adoc
Labels: documentation

#673 Fix JobTracker migration sample
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
Labels: backport to all versions

#680 Fixing project directory structure (#663)
  docs/modules/pipelines/pages/stream-processing-client.adoc
Labels: bug, backport to 5.1, backport to 5.0, backport to 5.2

#681 Removing interactive buttons due to deprecated tool.
  docs/modules/sql/pages/get-started-sql-files.adoc
  docs/modules/sql/pages/get-started-sql.adoc
  docs/modules/sql/pages/learn-sql.adoc
Labels: bug, backport to 5.1, backport to 5.0, backport to 5.2

#682 Fixing incorrect Python method
  docs/modules/data-structures/pages/updating-map-entries.adoc
Labels: bug, documentation, backport to 5.1, backport to 5.0, backport to 5.2

#683 Fixing link for Hazelcast Connector for Kafka on Lenses
  docs/modules/plugins/pages/other-integrations.adoc
Labels: bug, backport to 5.1, backport to 5.0, backport to 5.2

#677 DOCS-408 Jet Job Improvements
  docs/modules/events/pages/distributed-events.adoc
  docs/modules/pipelines/pages/job-management.adoc
  docs/modules/pipelines/pages/job-monitoring.adoc
  docs/modules/pipelines/partials/nav.adoc
  docs/modules/troubleshoot/pages/error-handling.adoc
Labels: documentation, backport to beta

#676 Applying the "external data store -> data link" change.
  docs/modules/external-data-stores/pages/external-data-stores.adoc
Labels: documentation, backport to beta

#675 DOCS-401_Kafka_Connect_Source_Connector
  docs/modules/ingest/pages/overview.adoc
  docs/modules/integrate/pages/connectors.adoc
  docs/modules/integrate/pages/kafka-connect-connectors.adoc
  docs/modules/integrate/partials/nav.adoc
  docs/modules/pipelines/pages/custom-stream-source.adoc
Labels: documentation

#689 Removing the link to AWS Deployment Guide temporarily.
  docs/modules/deploy/pages/deploying-on-aws.adoc
Labels: backport to 5.1, backport to 5.0, backport to beta, backport to 5.2

#690 Adding behind-the-scenes details of CP member shutdowns.
  docs/modules/cp-subsystem/pages/management.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#695 Updated the doc
  docs/modules/troubleshoot/pages/recovery-clients.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#691 DOCS-408 Updates to monitoring notes and minor updates
  docs/modules/pipelines/pages/job-monitoring.adoc
  docs/modules/test/pages/testing.adoc
Labels: backport to beta
