Repository hazelcast/hz-docs, pull requests merged in 2023-02, with the labels that each got.

#646 Fixing Persistence metric names and descriptions [DOCS-322]
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#647 Fixing alphabetical order of persistence metrics
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#628 Add compact binary specification API-1759
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/compact-binary-specification.adoc
  docs/modules/architecture/partials/nav.adoc
  docs/modules/serialization/pages/compact-serialization.adoc
Labels: documentation, Source: Internal, backport to 5.2

#650 Adding note for K8 service-name
  docs/modules/deploy/pages/configuring-kubernetes.adoc
Labels: backport to 5.1, backport to 5.0

#651 Adding content for RR to be used for non-HD -> HD
  docs/modules/data-structures/pages/setting-data-format.adoc
  docs/modules/maintain-cluster/pages/rolling-upgrades.adoc
Labels: enhancement, backport to 5.1, backport to 5.0, backport to 5.2

#652 Typo fix in CNAME content.
  docs/modules/clients/pages/java.adoc
Labels: bug, backport to 5.1, backport to 5.0, backport to 5.2

#654 DOCS-388 Update support statement for IBM_ZOS
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: backport to 5.2

#656 DOCS-392_Update_footnote_text
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: backport to 5.2

#661 Adding IMDSv2 content.
  docs/modules/deploy/pages/deploying-on-aws.adoc
Labels: documentation, enhancement, backport to 5.2

#662 Removing the non-working Katacoda interactive.
  docs/modules/getting-started/pages/get-started-cli.adoc
Labels: backport to 5.1, backport to 5.2

#666 Fixes #665 Update to Apply a Custom Transform with Python
  docs/modules/pipelines/pages/python.adoc
Labels: backport to 5.2

#668 Fix XML config example for custom ByteArraySerializer
  docs/modules/serialization/pages/custom-serialization.adoc
Labels: backport to 5.1, backport to 5.0
