Repository hazelcast/hz-docs, pull requests merged in 2023-06, with the labels that each got.

#765 DOCS-556 Update Tiered Storage Overview
  docs/modules/tiered-storage/pages/overview.adoc
Labels: backport to 5.3

#760 Adding Platform 5.3.1 RN.
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-3-1.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#768 Adding RN for Platform 5.2.4 release.
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-2-2.adoc
  docs/modules/release-notes/pages/5-2-4.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#769 DOCS-551_Deprecation notice for transactions
  docs/modules/clients/pages/java.adoc
  docs/modules/cluster-performance/pages/best-practices.adoc
  docs/modules/integrate/pages/jdbc-connector.adoc
  docs/modules/integrate/pages/jms-connector.adoc
  docs/modules/performance/pages/pipelining.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
  docs/modules/transactions/pages/creating-a-transaction-interface.adoc
  docs/modules/transactions/pages/providing-xa-transactions.adoc
Labels: backport to 5.3

#763 DOCS-359 Removal of Intel Support
  docs/modules/fault-tolerance/partials/nav.adoc
  docs/modules/storage/pages/high-density-memory.adoc
  docs/modules/storage/pages/persistence-on-intel.adoc
Labels: backport to 5.2, backport to 5.3

#670 DOCS-404 Updates to Supported Versions for 5.3
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: backport to 5.3

#773 Adding 5.1.7 RN.
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-1-7.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#777 Replacing Environment content with links
  docs/modules/security/pages/fips-140-2.adoc
Labels: enhancement

#775 [DOCS-483] - Add SQL permissions content for data connection statements.
  docs/modules/security/pages/native-client-security.adoc
Labels: backport to 5.3

#779 Fixes #771
  docs/modules/clusters/pages/discovering-native-clients.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#780 Fixes #762
  docs/modules/clusters/pages/partition-group-configuration.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#782 Update TCP tuning section
  docs/modules/cluster-performance/pages/performance-tuning.adoc
Labels: bug, backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#778 Adding RN for Platform 5.0.5.
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-0-5.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#761 Add Mongo to SQL connector list [HZ-2502]
  docs/modules/integrate/pages/connectors.adoc
  docs/modules/sql/pages/mapping-to-mongo.adoc
Labels: enhancement, Team: Platform
