Repository hazelcast/hz-docs, pull requests merged in 2024-08, with the labels that each got.

#1244 Fix pdf conversion error [REL-295][v/5.5]
  docs/modules/cp-subsystem/pages/configuration.adoc
Labels: bug

#1247 Fix duplicate links in configuration-guide.adoc
  docs/modules/mapstore/pages/configuration-guide.adoc
Labels: backport to all versions

#1224 Add vector collection permissions
  docs/modules/security/pages/native-client-security.adoc
Labels: forwardport to snapshot

#1231 Add more vector search tuning tips [AI-134]
  docs/modules/data-structures/pages/vector-search-overview.adoc
Labels: backport to 5.5

#1243 Add docs for hazelcast.async.join.strategy.enabled
  docs/modules/ROOT/pages/system-properties.adoc
Labels: enhancement, backport to 5.4, backport to 5.5

#1233 Update client versions
  docs/antora.yml
Labels: backport to 5.4, backport to 5.5

#1258 Lts update
  docs/modules/maintain-cluster/pages/rolling-upgrades.adoc
  docs/modules/migrate/pages/lts.adoc
Labels: backport to 5.5

#1252 Improve coherence between 'Serializing Pipelines' examples
  docs/modules/pipelines/pages/serialization.adoc
Labels: documentation, backport to all versions

#1222 Best Practices to Prevent OOM with IMap API Calls [CORE-153]
  docs/modules/ROOT/nav.adoc
  docs/modules/cluster-performance/pages/best-practices.adoc
  docs/modules/cluster-performance/pages/bulk-read-operations.adoc
  docs/modules/cluster-performance/pages/imap-bulk-read-operations.adoc
Labels: documentation
