Repository hazelcast/hz-docs, pull requests merged in 2024-03, with the labels that each got.

#1034 Update docs to detail unsupported Tiered Storage functionality for 5.4 [HZ-4381]
  docs/modules/tiered-storage/pages/overview.adoc
Labels: documentation

#1044 Fixes DOCS-687
  docs/modules/ROOT/pages/system-properties.adoc
  docs/modules/data-structures/pages/preventing-out-of-memory.adoc
Labels: backport to all versions, backport to beta-2, backport to 5.4

#1046 Add data structure metadata notice to Persistence overview.
  docs/modules/data-structures/pages/managing-map-memory.adoc
  docs/modules/storage/pages/persistence.adoc
Labels: backport to beta-2, backport to 5.3, backport to 5.4

#1048 Update monitoring.adoc
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2

#1045 Correct UCN Namespace definition key
  docs/modules/clusters/pages/ucn-enable.adoc
  docs/modules/clusters/pages/ucn-member-side.adoc
  docs/modules/clusters/pages/ucn-non-associated.adoc
Labels: backport to beta-2, backport to 5.4

#1041 Fix WAN static discovery properties description
  docs/modules/wan/pages/tuning.adoc
Labels: backport to 5.4

#1055 Added character data mapping for Postgres.
  docs/modules/sql/pages/mapping-to-jdbc.adoc
Labels: backport to beta-2, backport to 5.4

#1050 RN for v5.4.0
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
  docs/modules/release-notes/pages/5-4-0.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#1057 Describe recommendations for destroy method [HZ-4563]
  docs/modules/data-structures/pages/distributed-data-structures.adoc
Labels: backport to 5.3

#1056 Fixes DOCS-837
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/pipelines/pages/configuring-jobs.adoc
  docs/modules/pipelines/pages/job-monitoring.adoc
Labels: backport to all versions, backport to beta-2, backport to 5.4

#1047 Tiered Storage manual [HZ-4383]
  docs/modules/tiered-storage/pages/capacity-planning.adoc
  docs/modules/tiered-storage/pages/compactor.adoc
  docs/modules/tiered-storage/pages/configuration.adoc
  docs/modules/tiered-storage/pages/overview.adoc
  docs/modules/tiered-storage/pages/performance.adoc
  docs/modules/tiered-storage/pages/troubleshooting.adoc
  docs/modules/tiered-storage/partials/nav.adoc
Labels: documentation, backport to beta-2, backport to 5.4
