Repository hazelcast/hz-docs, pull requests merged in 2024-11, with the labels that each got.

#1364 Add AccessControlException deprecation note
  docs/modules/security/pages/security-interceptor.adoc
Labels: documentation, backport to 5.5

#1052 [CN-1092][CN-1104]: Helm Upgrade Guide
  docs/modules/kubernetes/pages/helm-hazelcast-enterprise-chart.adoc
  docs/modules/kubernetes/pages/helm-upgrade-guide.adoc
  docs/modules/kubernetes/partials/nav.adoc
Labels: backport to all versions, Automation: PR auto closed

#1359 Remove hardcoded `Editions` content [DI-333]
  docs/modules/getting-started/pages/editions.adoc
Labels: backport to all versions

#1378 Global check links
  .github/workflows/validate.yml
  .gitignore
  check-links-playbook.yml
  package-lock.json
  package.json
Labels: backport to all versions

#1381 doc-bug-579: added caution about earlier versions
  docs/modules/kubernetes/pages/kubernetes-persistence.adoc
Labels: backport to all versions

#1392 Update `CODEOWNERS` to use `documentation` group [DOC-256]
  .github/CODEOWNERS
Labels: backport to all versions

#1200 Update vector-collections.adoc
  docs/modules/data-structures/pages/vector-collections.adoc
Labels: backport to 5.5

#1366 Add vector collection backup documentation, update after upgrade to JVector 3 [AI-155] [AI-230]
  docs/modules/data-structures/pages/distributed-data-structures.adoc
  docs/modules/data-structures/pages/vector-collections.adoc
  docs/modules/data-structures/pages/vector-search-overview.adoc
  docs/modules/fault-tolerance/pages/backups.adoc
Labels: Type: Enhancement

#1369 Fix schema version definition in `understanding-configuration`
  docs/modules/configuration/pages/understanding-configuration.adoc
Labels: backport to all versions

#1401 DOC-279: add blog link and description to page
  docs/modules/ROOT/pages/ask-ai.adoc
Labels: backport to 5.5

#1407 Fix `id assigned to anchor already in use: columns` warning [DOC-260]
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
Labels: backport to 5.5
