Repository hazelcast/hz-docs, pull requests merged in 2024-06, with the labels that each got.

#1121 Add details about how the dynamic configuration update REST API works [DEX-115]
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
Labels: documentation, Type: Enhancement

#1131 Formatting fixes
  docs/modules/configuration/pages/configuring-programmatically.adoc
  docs/modules/data-connections/pages/mongo-dc-configuration.adoc
  docs/modules/kubernetes/pages/kubernetes-auto-discovery.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
Labels: backport to all versions

#1135 Considerations for Repartitioning and Migration [HZG-27]
  docs/modules/ROOT/pages/production-checklist.adoc
Labels: backport to 5.4

#1108 Clarification about client use public ip property
  docs/modules/clients/pages/java.adoc
Labels: backport to all versions

#1111 Update outdated infor about client versions
  docs/modules/maintain-cluster/pages/rolling-upgrades.adoc
Labels: backport to all versions, forwardport to snapshot

#1147 Add note to adv network configuration docs w.r.t endpoint overlaps
  docs/modules/clusters/pages/network-configuration.adoc
Labels: backport to 5.4
