Repository hazelcast/hz-docs, pull requests merged in 2024-05, with the labels that each got.

#1102 Add link to Operator docs for RU
  docs/modules/maintain-cluster/pages/rolling-upgrades.adoc
Labels: backport to all versions

#1090 DOCS-874: add TPC system properties
  docs/modules/ROOT/pages/system-properties.adoc
Labels: backport to 5.4

#1107 DOCS-708: remove jet-start.sh links
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/migrate/pages/upgrading-from-jet.adoc
Labels: backport to all versions

#1097 Create Documentation for Enterprise Rest API [DEX-78]
  antora-playbook.yml
  docs/modules/clients/partials/rest-deprecation.adoc
  docs/modules/maintain-cluster/images/rest-api-swagger-clicking-execute-button.png
  docs/modules/maintain-cluster/images/rest-api-swagger-clicking-try-it-out-button.png
  docs/modules/maintain-cluster/images/rest-api-swagger-expanding-an-endpoint.png
  docs/modules/maintain-cluster/images/rest-api-swagger-listed-endpoints.png
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
  docs/modules/maintain-cluster/pages/rest-api-swagger.adoc
  docs/modules/maintain-cluster/pages/rest-api.adoc
  docs/modules/maintain-cluster/partials/nav.adoc
  lib/swagger-ui-block-macro.js
  package.json
Labels: documentation

#1119 DOCS-822: minor text tweaks and backport
  docs/modules/ROOT/pages/index.adoc
Labels: backport to all versions
