Repository hazelcast/hz-docs, pull requests merged in 2024-01, with the labels that each got.

#941 Add the documentation for ReliableMessageListener [API-2182]
  docs/modules/data-structures/pages/reliable-topic.adoc
  docs/modules/events/pages/distributed-events.adoc
  docs/modules/events/pages/object-events.adoc
Labels: documentation, enhancement

#926 Update WAN publisher description
  docs/modules/wan/pages/wan.adoc
Labels: documentation, forwardport to snapshot

#958 Remove outdated garbage collector information
  docs/modules/troubleshoot/pages/remedies-for-alerts.adoc
Labels: Source: Internal, backport to 5.3

#956 Remove references to Java 8/9
  docs/modules/cluster-performance/pages/performance-tuning.adoc
  docs/modules/security/pages/integrating-openssl.adoc
  docs/modules/security/pages/tls-ssl.adoc
  docs/modules/serialization/pages/compact-serialization.adoc
Labels: Source: Internal, backport to 5.3

#959 Enhancing write-behind batching content
  docs/modules/mapstore/pages/implement-a-mapstore.adoc
Labels: enhancement

#960 [CN-1117] Remove all PCF/TAS references
  check-links-playbook.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/faq.adoc
  docs/modules/clusters/pages/discovery-mechanisms.adoc
  docs/modules/deploy/pages/deploying-in-vmware-tanzu.adoc
  docs/modules/deploy/pages/versioning-compatibility.adoc
  docs/modules/getting-started/pages/editions.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/migrate/pages/migration-tool-imdg.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#970 Removing the irrelevant caution from JDBC connector content.
  docs/modules/integrate/pages/jdbc-connector.adoc
Labels: backport to 5.3

#962 Remove AdoptOpenJDK references
  docs/modules/getting-started/pages/get-started-binary.adoc
  docs/modules/getting-started/pages/get-started-java.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/pipelines/pages/stream-processing-client.adoc
  docs/modules/storage/pages/backing-up-persistence.adoc
Labels: backport to all versions, Source: Internal

#965 Document Oracle Double Quotes Behavior
  docs/modules/sql/pages/mapping-to-jdbc.adoc
Labels: backport to 5.3

#976 Fix WAN Replication / Advanced Features typo
  docs/modules/wan/pages/advanced-features.adoc
Labels: documentation, backport to all versions, Source: Internal

#975 Update capacity-planning.adoc
  docs/modules/ROOT/pages/capacity-planning.adoc
Labels: forwardport to snapshot

#969 Document UDT improvements and breaking changes [HZ-3497] [HZ-3686]
  docs/modules/sql/pages/user-defined-types.adoc
Labels: enhancement

#972 Add static endpoint health checking documentation [HZ-3385]
  docs/modules/wan/pages/defining-wan-replication.adoc
  docs/modules/wan/pages/tuning.adoc
Labels: documentation

#984 DOCS-751: updated supported architectures note
  docs/modules/deploy/pages/versioning-compatibility.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
Labels: backport to 5.3
