Repository hazelcast/hz-docs, pull requests merged in 2024-09, with the labels that each got.

#1265 Update hazelcast-clients.adoc
  docs/modules/clients/pages/hazelcast-clients.adoc
Labels: forwardport to snapshot

#1288 Feast diagrams
  docs/modules/ROOT/images/feast_batch.png
  docs/modules/ROOT/images/feast_streaming.png
  docs/modules/integrate/pages/feature-engineering-with-feast.adoc
  docs/modules/integrate/pages/streaming-features-with-feast.adoc
Labels: backport to 5.5

#1295 Update nav for Develop and Build changes
  docs/modules/ROOT/nav.adoc
Labels: backport to all versions

#1297 DOCS-903: add dependencies and POJO tip; backport type-name
  docs/modules/mapstore/pages/configuring-a-generic-maploader.adoc
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
Labels: backport to 5.3, backport to 5.4, backport to 5.5
