Repository hazelcast/hz-docs, pull requests merged in 2024-12, with the labels that each got.

#1412 Add note about limit indirectly impacting quality [AI-269]
  docs/modules/data-structures/pages/vector-collections.adoc
Labels: backport to 5.5

#1416 DOC-260: fix dupe links
  docs/modules/mapstore/pages/configuring-a-generic-maploader.adoc
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
Labels: forwardport to snapshot

#1421 DOC-285 - update RHEL support
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: backport to 5.4, backport to 5.5

#1417 Data connection
  docs/modules/ROOT/nav.adoc
  docs/modules/data-connections/pages/build-map-loader-data-connection.adoc
  docs/modules/data-connections/pages/build-pipeline-service-data-connection.adoc
  docs/modules/data-connections/pages/data-connection-service.adoc
  docs/modules/data-connections/partials/nav.adoc
Labels: backport to 5.5

#1383 Add UCN support in Jet documentation [HZG-194]
  docs/modules/clusters/pages/user-code-namespaces.adoc
  docs/modules/clusters/partials/ucn-migrate-tip.adoc
  docs/modules/pipelines/pages/cdc-join.adoc
  docs/modules/pipelines/pages/configuring-jobs.adoc
  docs/modules/pipelines/pages/job-update.adoc
  docs/modules/sql/pages/create-job.adoc
Labels: documentation

#1433 GH issues 1428: remove reference to ZGC being experimental
  docs/modules/ROOT/pages/capacity-planning.adoc
Labels: backport to all versions

#1438 GitHub issue 1376 - XML config error
  docs/modules/security/pages/client-authorization.adoc
Labels: backport to all versions

#1442 GitHub Issue 1437 - update links to use os-version
  docs/modules/data-structures/pages/map-config.adoc
Labels: backport to all versions

#1446 Link fixes
  docs/modules/data-structures/pages/fencedlock.adoc
  docs/modules/deploy/pages/deploying-on-azure.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/integrate/pages/cdc-connectors.adoc
  docs/modules/pipelines/pages/cdc.adoc
  docs/modules/pipelines/pages/spring-boot.adoc
  docs/modules/pipelines/pages/submitting-jobs.adoc
Labels: backport to all versions

#1450 Revert "Revert "Correct YAML/XML security config""
  docs/modules/configuration/pages/configuring-declaratively.adoc
  docs/modules/security/pages/client-authorization.adoc
Labels: backport to all versions

#1431 Vector collection supports dynamic configuration [AI-85] [AI-86]
  docs/modules/configuration/pages/dynamic-config.adoc
Labels: backport to 5.5
