Repository hazelcast/hz-docs, pull requests merged in 2024-04, with the labels that each got.

#1065 Fix link to lite members [DOCS-844]
  docs/modules/architecture/pages/data-partitioning.adoc
Labels: backport to all versions, backport to beta-2, backport to 5.4

#1070 chore: fix typo in the docs
  docs/modules/sql/pages/improving-performance.adoc
Labels: forwardport to snapshot, backport to beta-2, backport to 5.2, backport to 5.4

#1058 Update WAN Rest API with target scope information [HZ-4594]
  docs/modules/wan/pages/rest-api.adoc
Labels: documentation, backport to all versions, backport to beta-2, backport to 5.4

#1071 Remove redundant `docker pull` from installation instructions
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
Labels: enhancement, backport to all versions

#1075 Fixes DOCS-259
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to all versions, backport to beta-2, backport to 5.4

#1077 Update documentation support links
  docs/modules/getting-started/pages/get-started-cli.adoc
  docs/modules/getting-started/pages/resources.adoc
  docs/modules/getting-started/pages/support.adoc
Labels: backport to all versions

#1076 Fix code samples link
  docs/modules/getting-started/pages/resources.adoc
Labels: backport to all versions

#1074 Update java.adoc
  docs/modules/clients/pages/java.adoc
Labels: forwardport to snapshot, backport to 5.1, backport to 5.0, backport to beta-2, backport to 5.2, backport to 5.4

#1087 Fixes 1081
  docs/modules/cp-subsystem/pages/configuration.adoc
Labels: backport to all versions

#1089 Fixing config file URLs of stable versions for future releases.
  docs/modules/configuration/pages/configuring-declaratively.adoc
Labels: bug

#1096 Fix external links.
  docs/modules/data-structures/pages/map-config.adoc
  docs/modules/integrate/pages/cdc-connectors.adoc
  docs/modules/maintain-cluster/pages/monitoring.adoc
  docs/modules/pipelines/pages/cdc-database-setup.adoc
Labels: backport to all versions

#1098 Fix link formatting.
  docs/modules/ROOT/pages/system-properties.adoc
Labels: backport to all versions

#1099 Fix XML/YAML for UCN
  docs/modules/clusters/pages/ucn-member-side.adoc
Labels: backport to 5.4
