Repository hazelcast/hz-docs, pull requests merged in 2024-02, with the labels that each got.

#987 stream-processing-client.adoc: wrong description of TestSources.itemStream
  docs/modules/pipelines/pages/stream-processing-client.adoc
Labels: forwardport to snapshot, backport to 5.1, backport to 5.0, backport to 5.2

#993 Removing irrelevant deprecation notice for JMS connector.
  docs/modules/integrate/pages/jms-connector.adoc
Labels: backport to 5.3

#986 [CN-1101] Update Adding Custom Jar Page
  docs/modules/kubernetes/pages/helm-adding-custom-jar.adoc
Labels: backport to 5.1, backport to 5.2, backport to 5.3

#954 Removing Java 11 and updating related references [HZ-4062][HZ-4168]
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/ROOT/pages/production-checklist.adoc
  docs/modules/cluster-performance/pages/performance-tuning.adoc
  docs/modules/clusters/pages/network-configuration.adoc
  docs/modules/deploy/pages/versioning-compatibility.adoc
  docs/modules/getting-started/pages/get-started-binary.adoc
  docs/modules/getting-started/pages/get-started-java.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
  docs/modules/pipelines/pages/stream-processing-client.adoc
  docs/modules/security/pages/fips-140-2.adoc
  docs/modules/security/pages/integrating-openssl.adoc
Labels: enhancement

#1000 Dummy PR to test the GH actions in action.
  docs/modules/test/pages/testing.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#1005 DOCS-765: Remove /instance refs and update example files link
  docs/modules/configuration/pages/jet-configuration.adoc
Labels: backport to 5.1, backport to 5.0, backport to 5.2, backport to 5.3

#961 DOC-699 Updates for UCN
  antora-playbook-local.yml
  antora-playbook.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/cluster-performance/pages/performance-tuning.adoc
  docs/modules/clusters/pages/accessing-domain-objects.adoc
  docs/modules/clusters/pages/deploying-code-from-clients.adoc
  docs/modules/clusters/pages/deploying-code-on-member.adoc
  docs/modules/clusters/pages/legacy-ucd.adoc
  docs/modules/clusters/pages/ucn-data-structures.adoc
  docs/modules/clusters/pages/ucn-dynamic-client.adoc
  docs/modules/clusters/pages/ucn-dynamic-config.adoc
  docs/modules/clusters/pages/ucn-enable.adoc
  docs/modules/clusters/pages/ucn-member-side.adoc
  docs/modules/clusters/pages/ucn-migrate-ucd.adoc
  docs/modules/clusters/pages/ucn-non-associated.adoc
  docs/modules/clusters/pages/ucn-security.adoc
  docs/modules/clusters/pages/ucn-static-config.adoc
  docs/modules/clusters/pages/ucn-static-programmatic.adoc
  docs/modules/clusters/pages/user-code-namespaces.adoc
  docs/modules/clusters/partials/nav.adoc
  docs/modules/clusters/partials/ucn-migrate-tip.adoc
  docs/modules/computing/pages/entry-processor.adoc
  docs/modules/configuration/pages/dynamic-config.adoc
  docs/modules/integrate/pages/cdc-connectors.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-4.adoc
  docs/modules/pipelines/pages/cdc-join.adoc
  docs/modules/security/pages/native-client-security.adoc
  docs/modules/serialization/pages/serialization.adoc
  docs/modules/sql/pages/mapping-to-maps.adoc
Labels: backport to beta-2

#1012 Closes DOCS-724 - Document SQL Performance
  docs/modules/cluster-performance/pages/best-practices.adoc
  docs/modules/cluster-performance/pages/data-affinity.adoc
  docs/modules/cluster-performance/partials/nav.adoc
  docs/modules/sql/pages/partition-pruning.adoc
Labels: backport to beta-2

#1003 Replace Helm Chart redirection with Operator one
  docs/modules/kubernetes/pages/kubernetes-auto-discovery.adoc
Labels: backport to 5.2, backport to 5.3

#1019 Fixing unresolved link
  docs/modules/clusters/pages/deploying-code-on-member.adoc
Labels: backport to 5.1, backport to 5.0, backport to beta-2, backport to 5.2, backport to 5.3

#1028 Minor update (jobId -> jobName)
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to beta-2, backport to 5.3
