Repository hazelcast/hz-docs, pull requests merged in 2024-10, with the labels that each got.

#1275 Update UCN notices to mention incompatibility with Jet
  docs/modules/clusters/partials/ucn-migrate-tip.adoc
  docs/modules/pipelines/pages/cdc-join.adoc
Labels: backport to 5.4, backport to 5.5

#1189 Fix jetty plugin documentation link
  docs/modules/plugins/pages/web-session-replication.adoc
Labels: backport to all versions, forwardport to snapshot

#1282 Change documentation for "default" tag in map configuration
  docs/modules/data-structures/pages/map-config.adoc
Labels: Type: Enhancement

#1149 Add Debezium 2.x docs
  docs/modules/ROOT/nav.adoc
  docs/modules/integrate/pages/cdc-connectors.adoc
  docs/modules/integrate/pages/connectors.adoc
  docs/modules/integrate/pages/legacy-cdc-connectors.adoc
  docs/modules/pipelines/pages/cdc-database-setup.adoc
  docs/modules/pipelines/pages/cdc-join.adoc
  docs/modules/pipelines/pages/cdc-postgres.adoc
  docs/modules/pipelines/pages/cdc.adoc
Labels: backport to 5.5

#1313 Clarify (lack of) backup redistribution on data structure level [HZG-156]
  docs/modules/fault-tolerance/pages/backups.adoc
Labels: documentation, backport to all versions, Type: Enhancement

#1321 Update the javadoc link for the new client
  docs/modules/clients/pages/java.adoc
Labels: backport to 5.5

#1325 Update start_page and Messaging Connectors level
  antora-playbook.yml
  docs/modules/ROOT/nav.adoc
Labels: backport to 5.4, backport to 5.5

#1327 Add UTM link to hazelcast.com URLs
  docs/antora.yml
  docs/modules/ROOT/examples/helper/LicenseUtils.java
  docs/modules/cache/pages/overview.adoc
  docs/modules/clients/pages/hazelcast-clients.adoc
  docs/modules/cluster-performance/pages/performance-tips.adoc
  docs/modules/deploy/pages/choosing-a-deployment-option.adoc
  docs/modules/deploy/pages/deploying-on-aws.adoc
  docs/modules/getting-started/pages/editions.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/getting-started/pages/resources.adoc
  docs/modules/getting-started/pages/support.adoc
  docs/modules/kubernetes/pages/helm-hazelcast-enterprise-chart.adoc
  docs/modules/pipelines/pages/overview.adoc
  docs/modules/pipelines/pages/python.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
  docs/modules/troubleshoot/pages/remedies-for-alerts.adoc
Labels: backport to all versions
