Repository hazelcast/hz-docs, pull requests merged in 2024-07, with the labels that each got.

#1136 Enterprise REST API doc updates [DEX-146]
  docs/modules/ROOT/nav.adoc
  docs/modules/clients/partials/rest-deprecation.adoc
  docs/modules/getting-started/pages/get-started-rest-api-with-docker.adoc
  docs/modules/getting-started/pages/get-started-rest-api-with-java.adoc
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
  docs/modules/maintain-cluster/partials/nav.adoc
Labels: documentation

#1153 Update protocol documentation
  docs/modules/security/pages/integrating-openssl.adoc
Labels: documentation, backport to 5.4

#1142 Add missing word
  docs/modules/cache/pages/overview.adoc
Labels: backport to all versions, forwardport to snapshot

#1158 DOC-79: 5.4.1 Release Notes
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/release-notes/pages/5-4-1.adoc
  docs/modules/release-notes/pages/releases.adoc
Labels: Release Notes

#1156 Add tutorial for REST Dynamic Config [DEX-113]
  docs/modules/ROOT/nav.adoc
  docs/modules/maintain-cluster/pages/dynamic-config-via-rest.adoc
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
Labels: documentation

#1168 Clarify CP Leadership Priority option
  docs/modules/cp-subsystem/pages/configuration.adoc
Labels: documentation, backport to all versions

#1182 Clarify nested object fields status for SQL
  docs/modules/query/pages/overview.adoc
  docs/modules/sql/pages/querying-maps-sql.adoc
Labels: enhancement, backport to 5.4

#1197 Update cluster routing mode compatibility for TPC [ESC-42]
  docs/modules/clients/pages/java.adoc
  docs/modules/cluster-performance/pages/thread-per-core-tpc.adoc
Labels: documentation

#1188 Add Note for REST dependency conflicts [DEX-210]
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
Labels: documentation, backport to 5.5

#1208 Various Java client updates & fixes [HZG-48]
  docs/modules/clients/pages/java.adoc
Labels: documentation, backport to 5.5

#1123 Add client connectivity logging property [HZ-4734]
  docs/modules/clients/pages/java.adoc
Labels: backport to 5.5

#1216 Fix NAV structure for categorise the data structures
  docs/modules/ROOT/nav.adoc
  docs/modules/clients/pages/hazelcast-clients.adoc
  docs/modules/clients/pages/java.adoc
  docs/modules/data-structures/partials/nav.adoc
Labels: backport to 5.5

#1217 Update name to Hazelcast Platform on drop down and update Nav
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/architecture/pages/architecture.adoc
  docs/modules/clients/pages/hazelcast-clients.adoc
  docs/modules/cluster-performance/pages/performance-tips.adoc
  docs/modules/cluster-performance/pages/performance-tuning.adoc
  docs/modules/clusters/partials/nav.adoc
  docs/modules/computing/pages/distributed-computing.adoc
  docs/modules/computing/partials/nav.adoc
  docs/modules/cp-subsystem/pages/configuration.adoc
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
  docs/modules/cp-subsystem/pages/management.adoc
  docs/modules/data-structures/pages/entry-processor.adoc
  docs/modules/data-structures/pages/fencedlock.adoc
  docs/modules/data-structures/pages/iatomiclong.adoc
  docs/modules/data-structures/pages/iatomicreference.adoc
  docs/modules/data-structures/pages/icountdownlatch.adoc
  docs/modules/data-structures/pages/isemaphore.adoc
  docs/modules/data-structures/pages/setting-data-format.adoc
  docs/modules/data-structures/pages/updating-map-entries.adoc
  docs/modules/data-structures/partials/nav.adoc
  docs/modules/mapstore/pages/implement-a-mapstore.adoc
Labels: backport to 5.5

#1221 Update to connectors & data structures overview
  docs/modules/data-structures/pages/distributed-data-structures.adoc
  docs/modules/integrate/pages/socket-connector.adoc
Labels: backport to 5.5

#1227 Update nav for Operate & Manage
  docs/modules/ROOT/nav.adoc
  docs/modules/fault-tolerance/partials/nav.adoc
Labels: backport to 5.5
