Repository hazelcast/hz-docs, pull requests merged in 2025-04, with the labels that each got.

#1636 Correct MultiMap supported events [HZG-113]
  docs/modules/ROOT/examples/distributedevents/ExampleEntryListener.java
  docs/modules/events/pages/object-events.adoc
  docs/modules/pipelines/pages/object-events.adoc
Labels: backport to all versions, java

#1645 Update best-practices.adoc
  docs/modules/cluster-performance/pages/best-practices.adoc
Labels: backport to 5.4, backport to 5.5

#1644 Delete docs/modules/ROOT/pages/production-checklist.adoc
  docs/modules/ROOT/pages/production-checklist.adoc
Labels: backport to 5.4, backport to 5.5

#1637 Clarify WAN queue capacity behaviour [HZG-308]
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/wan/pages/tuning.adoc
Labels: backport to all versions

#1662 Fix `page-enterprise` label on `get-started-rest-api-with-java.adoc`
  docs/modules/data-connections/pages/build-map-loader-data-connection.adoc
  docs/modules/data-connections/pages/build-pipeline-service-data-connection.adoc
  docs/modules/getting-started/pages/get-started-rest-api-with-java.adoc
  docs/modules/maintain-cluster/pages/dynamic-config-via-rest.adoc
  docs/modules/migrate/pages/lts.adoc
Labels: backport to 5.5

#1665 Update versioning-compatibility.adoc
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: forwardport to snapshot

#1660 change some of the SQL "no" to "n/a"
  docs/modules/configuration/pages/dynamic-config.adoc
Labels: backport to 5.5

#1669 Fix partition counts link
  docs/modules/cluster-performance/pages/performance-tips.adoc
Labels: forwardport to snapshot

#1671 improve documentation for WAN sync progress
  docs/modules/wan/pages/rest-api.adoc
Labels: backport to 5.5

#1648 DOC-435: remove standalone refs
  docs/modules/clients/pages/java.adoc
Labels: backport to 5.5

#1627 DOC-430: remove Flow glossary terms
  docs/modules/ROOT/pages/glossary.adoc
Labels: backport to 5.4, backport to 5.5
