Repository hazelcast/hz-docs, pull requests merged in 2025-03, with the labels that each got.

#1587 Backport custom classes note to map-connector.adoc
  docs/modules/integrate/pages/map-connector.adoc
Labels: backport to 5.4

#1588 Backport clarify MapLoader interaction behaviour
  docs/modules/mapstore/pages/mapstore-triggers.adoc
Labels: backport to 5.4, backport to 5.5

#1597 Fix authentication yaml indent
  docs/modules/security/pages/simple-authentication.adoc
Labels: forwardport to snapshot

#1609 doc bug 1606 - update get-started-binary
  docs/modules/getting-started/pages/get-started-binary.adoc
Labels: backport to all versions, forwardport to snapshot

#1616 Fix some broken links in Capacity planning
  docs/modules/ROOT/pages/capacity-planning.adoc
  docs/modules/cluster-performance/pages/performance-tips.adoc
Labels: backport to 5.5

#1619 Fix typo in `capacity-planning.adoc`
  docs/modules/ROOT/pages/capacity-planning.adoc
Labels: backport to all versions

#1626 DOC-428 - remove references to tiered storage
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/ROOT/pages/phone-homes.adoc
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
  docs/modules/mapstore/pages/configuration-guide.adoc
  docs/modules/sql/pages/create-index.adoc
  docs/modules/tiered-storage/pages/capacity-planning.adoc
  docs/modules/tiered-storage/pages/compactor.adoc
  docs/modules/tiered-storage/pages/configuration.adoc
  docs/modules/tiered-storage/pages/overview.adoc
  docs/modules/tiered-storage/pages/performance.adoc
  docs/modules/tiered-storage/pages/troubleshooting.adoc
Labels: backport to all versions

#1628 DOC-428 tiered storage 5.5
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/ROOT/pages/phone-homes.adoc
  docs/modules/maintain-cluster/pages/enterprise-rest-api.adoc
  docs/modules/mapstore/pages/configuration-guide.adoc
  docs/modules/sql/pages/create-index.adoc
  docs/modules/tiered-storage/pages/capacity-planning.adoc
  docs/modules/tiered-storage/pages/compactor.adoc
  docs/modules/tiered-storage/pages/configuration.adoc
  docs/modules/tiered-storage/pages/overview.adoc
  docs/modules/tiered-storage/pages/performance.adoc
  docs/modules/tiered-storage/pages/troubleshooting.adoc
  docs/modules/tiered-storage/partials/nav.adoc
Labels: backport to all versions
