Repository hazelcast/hz-docs, pull requests merged in 2025-02, with the labels that each got.

#1513 Remove dead Hazelcast/Optane Intel blog link
  docs/modules/storage/pages/persistence-on-intel.adoc
Labels: backport to all versions

#1512 Update 'hazelcast.diagnostics.memberinfo.period.seconds' Property To Use 'seconds' In Plural
  docs/modules/ROOT/pages/system-properties.adoc
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: backport to all versions

#1510 Some clarifications about data persistence [HZG-257]
  docs/modules/storage/pages/persistence.adoc
Labels: backport to all versions

#1523 Improve UCN migration page + fix indentation [SUP-799]
  docs/modules/clusters/pages/ucn-enable.adoc
  docs/modules/clusters/pages/ucn-member-side.adoc
  docs/modules/clusters/pages/ucn-migrate-ucd.adoc
  docs/modules/clusters/pages/ucn-non-associated.adoc
Labels: backport to 5.4, backport to 5.5

#1525 Explain potential fragmentation issues for the POOLED memory allocator [HZG-256]
  docs/modules/storage/pages/high-density-memory.adoc
Labels: backport to all versions

#1536 Correct maximum recommended clients per member
  docs/modules/clients/pages/client-overview.adoc
Labels: Type: Enhancement, backport to 5.3, backport to 5.4, backport to 5.5

#1538 Update Javadoc links to use OS version [DI-425]
  docs/modules/ROOT/pages/list-of-metrics.adoc
  docs/modules/clients/pages/java.adoc
  docs/modules/cluster-performance/pages/data-affinity.adoc
  docs/modules/cluster-performance/pages/imap-bulk-read-operations.adoc
  docs/modules/cluster-performance/pages/near-cache.adoc
  docs/modules/cluster-performance/pages/thread-per-core-tpc.adoc
  docs/modules/clusters/pages/ucn-security.adoc
  docs/modules/computing/pages/durable-executor-service.adoc
  docs/modules/computing/pages/executor-service.adoc
  docs/modules/computing/pages/scheduled-executor-service.adoc
  docs/modules/configuration/pages/configuring-declaratively.adoc
  docs/modules/configuration/pages/configuring-programmatically.adoc
  docs/modules/data-connections/pages/data-connection-service.adoc
  docs/modules/data-connections/pages/data-connections-configuration.adoc
  docs/modules/data-structures/pages/cardinality-estimator-service.adoc
  docs/modules/data-structures/pages/entry-processor.adoc
  docs/modules/data-structures/pages/listening-for-map-entries.adoc
  docs/modules/data-structures/pages/replicated-map.adoc
  docs/modules/data-structures/pages/vector-collections.adoc
  docs/modules/deploy/pages/enterprise-licenses.adoc
  docs/modules/events/pages/object-events.adoc
  docs/modules/extending-hazelcast/pages/discovery-spi.adoc
  docs/modules/integrate/pages/custom-connectors.adoc
  docs/modules/integrate/pages/elasticsearch-connector.adoc
  docs/modules/integrate/pages/kafka-connector.adoc
  docs/modules/integrate/pages/legacy-cdc-connectors.adoc
  docs/modules/jcache/pages/icache.adoc
  docs/modules/maintain-cluster/pages/cluster-member-states.adoc
  docs/modules/maintain-cluster/pages/monitoring.adoc
  docs/modules/mapstore/pages/implement-a-mapstore.adoc
  docs/modules/mapstore/pages/mapstore-triggers.adoc
  docs/modules/migrate/pages/upgrading-from-imdg-3.adoc
  docs/modules/migrate/pages/upgrading-from-jet.adoc
  docs/modules/pipelines/pages/cdc-database-setup.adoc
  docs/modules/pipelines/pages/configuring-jobs.adoc
  docs/modules/pipelines/pages/custom-aggregate-operation.adoc
  docs/modules/pipelines/pages/grpc.adoc
  docs/modules/pipelines/pages/observables.adoc
  docs/modules/pipelines/pages/overview.adoc
  docs/modules/pipelines/pages/serialization.adoc
  docs/modules/pipelines/pages/transforms.adoc
  docs/modules/query/pages/predicate-overview.adoc
  docs/modules/release-notes/pages/5-3-0.adoc
  docs/modules/release-notes/pages/5-4-0.adoc
  docs/modules/security/pages/logging-auditable-events.adoc
  docs/modules/serialization/pages/implementing-portable-serialization.adoc
  docs/modules/serialization/pages/serializing-json.adoc
  docs/modules/spring/pages/transaction-manager.adoc
  docs/modules/sql/pages/alter-job.adoc
  docs/modules/sql/pages/create-data-connection.adoc
  docs/modules/sql/pages/sql-overview.adoc
  docs/modules/storage/pages/configuring-persistence.adoc
  docs/modules/transactions/pages/creating-a-transaction-interface.adoc
  docs/modules/transactions/pages/providing-xa-transactions.adoc
  docs/modules/troubleshoot/pages/error-handling.adoc
  docs/modules/wan/pages/advanced-features.adoc
Labels: backport to 5.5

#1540 Remove more `full-version` usages
  docs/antora.yml
  docs/modules/ROOT/examples/operator/bundle.yaml
  docs/modules/ROOT/examples/operator/hazelcast.yaml
  docs/modules/ROOT/examples/operator/hazelcast_expose_externally.yaml
  docs/modules/clients/pages/java.adoc
  docs/modules/deploy/pages/deploying-with-docker.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
  docs/modules/integrate/pages/cdc-connectors.adoc
  docs/modules/integrate/pages/file-connector.adoc
  docs/modules/integrate/pages/kafka-connect-connectors.adoc
  docs/modules/integrate/pages/kafka-connector.adoc
  docs/modules/integrate/pages/kinesis-connector.adoc
  docs/modules/integrate/pages/legacy-file-connector.adoc
  docs/modules/jcache/pages/setup.adoc
  docs/modules/management/pages/cluster-utilities.adoc
  docs/modules/pipelines/pages/cdc-join.adoc
  docs/modules/pipelines/pages/cdc-postgres.adoc
  docs/modules/pipelines/pages/cdc.adoc
  docs/modules/pipelines/pages/grpc.adoc
  docs/modules/pipelines/pages/kafka.adoc
  docs/modules/pipelines/pages/kinesis.adoc
  docs/modules/pipelines/pages/map-join.adoc
  docs/modules/pipelines/pages/pulsar.adoc
  docs/modules/pipelines/pages/python.adoc
  docs/modules/pipelines/pages/serialization.adoc
  docs/modules/pipelines/pages/stream-processing-client.adoc
  docs/modules/pipelines/pages/stream-processing-embedded.adoc
  docs/modules/pipelines/pages/windowing.adoc
  docs/modules/spring/pages/configuration.adoc
  docs/modules/sql/pages/mapping-to-a-file-system.adoc
  docs/modules/sql/pages/mapping-to-kafka.adoc
  docs/modules/sql/pages/mapping-to-mongo.adoc
  docs/modules/test/pages/testing.adoc
Labels: backport to 5.5

#1534 Clarify that GenericMapStore does not support domain object transformation [HZG-253]
  docs/modules/mapstore/pages/configuring-a-generic-mapstore.adoc
Labels: backport to all versions

#1548 Update CODEOWNERS across branches to use team
  .github/CODEOWNERS
Labels: backport to all versions

#1539 Fix MC Docker tags
  docs/modules/getting-started/pages/get-started-docker.adoc
  docs/modules/getting-started/pages/persistence.adoc
  docs/modules/getting-started/pages/wan.adoc
  docs/modules/migrate/pages/upgrading-from-jet.adoc
  docs/modules/pipelines/pages/stream-processing-client.adoc
Labels: backport to all versions

#1466 DOC-195 - Spring updates
  docs/modules/ROOT/nav.adoc
  docs/modules/spring/pages/add-caching.adoc
  docs/modules/spring/pages/best-practices.adoc
  docs/modules/spring/pages/configuration.adoc
  docs/modules/spring/pages/hibernate.adoc
  docs/modules/spring/pages/overview.adoc
  docs/modules/spring/pages/springaware.adoc
  docs/modules/spring/pages/transaction-manager.adoc
Labels: backport to 5.5

#1544 Correct maximum recommended clients per member [v5.5]
  docs/modules/clients/pages/hazelcast-clients.adoc
Labels: backport to 5.3, backport to 5.4

#1577 Update rolling upgrade MC version info
  docs/modules/maintain-cluster/pages/rolling-upgrades.adoc
Labels: backport to 5.5

#1572 Remove erroneous `WARNING` section from CDC docs
  docs/modules/pipelines/pages/cdc.adoc
Labels: backport to 5.5
