Repository hazelcast/hz-docs, pull requests merged in 2025-07, with the labels that each got.

#1746 Fix broken links
  docs/modules/getting-started/pages/editions.adoc
Labels: backport to 5.5

#1753 DOC-fix for Hazelcast enterprise configuration via helm
  docs/modules/kubernetes/pages/helm-hazelcast-enterprise-chart.adoc
Labels: backport to all versions

#1764 Improve IQueue semantics documentation
  docs/modules/data-structures/pages/queue.adoc
Labels: backport to all versions

#1772 ci: add typo check step to validate workflow and its configuration to prevent false positive
  docs/modules/ROOT/examples/security/CustomLoginModuleTest.java
  docs/modules/ROOT/pages/faq.adoc
  docs/modules/architecture/pages/architecture.adoc
  docs/modules/clients/pages/go-client-getting-started.adoc
  docs/modules/clients/pages/nodejs-client-getting-started.adoc
  docs/modules/cluster-performance/pages/performance-tips.adoc
  docs/modules/clusters/pages/ucn-static-config.adoc
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
  docs/modules/data-connections/pages/data-connection-service.adoc
  docs/modules/data-connections/pages/mongo-dc-configuration.adoc
  docs/modules/data-structures/pages/list.adoc
  docs/modules/integrate/pages/integrate-with-feast.adoc
  docs/modules/integrate/pages/streaming-features-with-feast.adoc
  docs/modules/management/pages/cluster-utilities.adoc
  docs/modules/migrate/pages/community-to-enterprise.adoc
  docs/modules/migrate/pages/data-migration-tool.adoc
  docs/modules/migrate/pages/lts.adoc
  docs/modules/pipelines/attachments/nasdaqlisted.txt
  docs/modules/pipelines/pages/cdc-database-setup.adoc
  docs/modules/query/pages/predicate-overview.adoc
  docs/modules/sql/pages/functions-and-operators.adoc
  docs/modules/sql/pages/improving-performance.adoc
Labels: backport to all versions

#1788 [EMGR-477] Reference IAtomicLong as an alternative for PNCounter
  docs/modules/data-structures/pages/pn-counter.adoc
Labels: backport to 5.5

#1787 Update java.adoc client connection strategy
  docs/modules/clients/pages/java.adoc
Labels: forwardport to snapshot

#1795 Use explicit version of docker image in vector collection example [DOC-238]
  docs/modules/data-structures/pages/vector-collections.adoc
Labels: backport to 5.5
