Repository hazelcast/hz-docs, pull requests merged in 2025-01, with the labels that each got.

#1404 Clarify default UCN behaviour
  docs/modules/clusters/pages/ucn-non-associated.adoc
Labels: enhancement

#1461 Clarify MapLoader interaction behaviour [HZG-289]
  docs/modules/mapstore/pages/mapstore-triggers.adoc
Labels: enhancement

#1468 Fix memberDN notation
  docs/modules/security/pages/ldap-authentication.adoc
Labels: forwardport to snapshot

#1473 Fix `forwardport` action parameter naming
  .github/workflows/forwardport.yml
Labels: backport to all versions

#1478 Disambiguate which kind of persistence is documented in the table [HZG-268]
  docs/modules/configuration/pages/dynamic-config.adoc
Labels: backport to all versions

#1483 Fix typo in VectorCollection example
  docs/modules/data-structures/pages/vector-collections.adoc
Labels: backport to 5.5

#1479 Use default partition count in example vector collection command [AI-195]
  docs/modules/data-structures/pages/vector-collections.adoc
Labels: backport to 5.5

#1485 Update versioning for Windows support, and clean up table structures.
  docs/modules/deploy/pages/versioning-compatibility.adoc
Labels: backport to 5.5

#1494 DOC-343 fix placeholder format
  docs/modules/security/pages/ldap-authentication.adoc
Labels: backport to all versions

#1495 DOC-343 - fix placeholder formatting
  docs/modules/security/pages/security-realms.adoc
Labels: backport to 5.3

#1465 Update RoutingMode package [HZG-251]
  docs/modules/ROOT/examples/clients/ExampleClientConfiguration.java
Labels: documentation

#1498 Document expensive IMap reporting threshold & property
  docs/modules/cluster-performance/pages/imap-bulk-read-operations.adoc
Labels: enhancement

#1501 Support backporting from non-`master` branches [DOC-370]
  .github/workflows/backport.yml
Labels: backport to all versions
