Repository hazelcast/hz-docs, pull requests merged in 2025-08, with the labels that each got.

#1799 Fix `backport` workflow permissions
  .github/workflows/backport-workflow.yml
Labels: backport to all versions

#1789 Fix dead `ndctl` installation link
  docs/modules/storage/pages/persistence-on-intel.adoc
Labels: backport to all versions

#1809 Add MULTI_MEMBER capacity planning docs [HZG-564]
  docs/modules/ROOT/pages/capacity-planning.adoc
Labels: documentation, backport to 5.5

#1811 1785-java-docs-maven: add Maven dependency
  docs/modules/clients/pages/java.adoc
Labels: backport to all versions

#1816 Clarify WAN sync behaviour [SUP-981]
  docs/modules/wan/pages/advanced-features.adoc
Labels: documentation, backport to all versions

#1815 hz-docs issue 1785 - annotate Maven install config
  docs/modules/clients/pages/java.adoc
  docs/modules/getting-started/pages/install-enterprise.adoc
  docs/modules/getting-started/pages/install-hazelcast.adoc
Labels: backport to all versions

#1823 Update client-authorization.adoc
  docs/modules/security/pages/client-authorization.adoc
Labels: backport to all versions, forwardport to snapshot

#1849 Doc issue 1308 - amend encryption note
  docs/modules/data-connections/pages/data-connections-configuration.adoc
Labels: backport to 5.4

#1848 Docs issue 1649 - update CP member description
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
Labels: backport to all versions

#1851 Docs issue 1649 - update CP member description
  docs/modules/cp-subsystem/pages/cp-subsystem.adoc
Labels: backport to 5.4
