Repository hazelcast/hz-docs, pull requests merged in 2025-09, with the labels that each got.

#1855 Remove enterprise refs from metrics page
  docs/modules/ROOT/pages/list-of-metrics.adoc
Labels: backport to 5.4

#1856 Add Job Placement Control to EE features list
  docs/modules/getting-started/pages/editions.adoc
Labels: backport to 5.5

#1858 Correctly mark new CDC connector as EE feature
  docs/modules/integrate/pages/cdc-connectors.adoc
Labels: backport to 5.5

#1859 Add complete example how to invoke embedding model from Jet pipeline
  docs/modules/integrate/pages/vector-collection-connector.adoc
Labels: backport to 5.5

#1863 Improve `Queue` `empty-queue-ttl` property description
  docs/modules/data-structures/pages/queue.adoc
Labels: backport to all versions

#1730 Add Dynamic Configuration Changes for `Diagnostics` [DEX-212]
  docs/modules/maintain-cluster/pages/monitoring.adoc
Labels: enhancement
